config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions" } 
  get '/users/current_user' => "users#the_current_user", as: :current_user
  resources :issues
  resources :users
  resources :issues do
    resources :comments
  end

  root 'issues#index'
  get '/issues/:issue_id/comments/:id/attachment' => "comments#show_attachment"
  post '/issues/:issue_id/comments/:id/attachment' => "comments#create_attachment"
  get '/issues/:id/attachment' => "issues#show_attachment"
  post '/issues/:id/attachment' => "issues#create_attachment"
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/watch' => "issues#watch", as: :watch
  
  put '/issues/:id/status' => "issues#update_status", as: :update_status
end

app/models/issue.rb
class Issue < ApplicationRecord
    belongs_to :user
    belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id, optional: true
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :watchers, dependent: :destroy
    validates :Title, :Type, :Priority, :Status, presence: true
    has_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" },
        :storage => :cloudinary,
        :path => 'issues/:id/:filename',
        :cloudinary_resource_type => :raw    
    def self.status
        ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
    end
    def self.type
        ["Bug", "Enhancement", "Proposal", "Task"]
    end
    def self.priority
        ["Trivial", "Minor", "Major", "Critical", "Blocker"]
    end

    do_not_validate_attachment_file_type :attachment
    
    default_scope { order(created_at: :desc) }
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  protect_from_forgery with: :null_session
  acts_as_token_authentication_handler_for User, fallback: :devise
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /issues
  # GET /issues.json
  
  def index
    respond_to do |format|
      @issues = Issue.all
      
      if params.has_key?(:assignee)
        if User.exists?(id: params[:assignee])
          @issues = @issues.where(assignee_id: params[:assignee])
        else
          format.json {render json: {"error":"User with id="+params[:assignee]+" does not exist"}, status: :unprocessable_entity}
        end
      end
      
      if params.has_key?(:type)
        @issues = @issues.where(Type: params[:type])
      end
      
      if params.has_key?(:priority)
        @issues = @issues.where(Priority: params[:priority])
      end
      
      if params.has_key?(:status)
        if params[:status] == "New&Open"
          @issues = @issues.where(Status: ["Open","New"])
        else
        @issues = @issues.where(Status: params[:status])
        end
      end
      
      if params.has_key?(:watcher)
        if User.exists?(id: params[:watcher])
          @issues = Issue.joins(:watchers).where(watchers:{user_id: params[:watcher]})
        else
          format.json {render json: {"error":"User with id="+params[:watcher]+" does not exist"}, status: :unprocessable_entity}
        end
      end

      format.html
      format.json {render json: @issues, status: :ok, each_serializer: IssueIndexSerializer}
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @issue, status: :ok, serializer: IssueSerializer}
    end
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.user_id = current_user.id
    respond_to do |format|
      if (issue_params.has_key?(:assignee_id) && issue_params[:assignee_id] != "" && !User.exists?(id: issue_params[:assignee_id]))
          format.json {render json: {"error":"User with id="+issue_params[:assignee_id]+" does not exist"}, status: :unprocessable_entity}
      else
        if @issue.save
          @watcher = Watcher.new
          @watcher.user_id = current_user.id
          @watcher.issue_id = @issue.id
          @watcher.save
          @issue.increment!("Watchers")
          format.html { redirect_to @issue }
          format.json { render json: @issue, status: :created, serializer: IssueSerializer }
        else
          format.html { render :new }
          format.json { render json: @issue.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if !User.exists?(id: params[:assignee_id])
          format.json {render json: {"error":"User with id="+params[:assignee_id]+" does not exist"}, status: :unprocessable_entity}
      else
        @issue_to_update = Issue.find(params[:id])
        @issue_to_update.update(issue_params)
        
        format.html { redirect_to @issue_to_update }
        format.json { render json: @issue_to_update, status: :ok, serializer: IssueSerializer}
      end
    end
  end
  
  def update_status
    respond_to do |format|
      @issue_to_update = Issue.find(params[:id])
      @issue_to_update.update_attribute("Status", params[:status])
      
      format.html { redirect_to @issue_to_update }
      format.json { render json: @issue_to_update, status: :ok }
    end
  end
  
  
  # POST /issues/{issue_id}/watch
  
  def watch
    respond_to do |format|
      @issue_to_watch = Issue.find(params[:id])
      if !Watcher.exists?(:issue_id => @issue_to_watch.id, :user_id => current_user.id)
        @watcher = Watcher.new
        @watcher.user_id = current_user.id
        @watcher.issue_id = @issue_to_watch.id
        @watcher.save
        @issue_to_watch.increment!("Watchers")
      else
        @watcher = Watcher.where(issue_id: params[:id], user_id: current_user.id).take
        @watcher.destroy
        @issue_to_watch.decrement!("Watchers")
      end
      if params[:view] == "index"
        format.html { redirect_to issues_url}
      else
        format.html { redirect_to @issue_to_watch}
      end
      format.json { render json: @issue_to_watch, status: :ok }
    end
  end
  
  
  # POST /issues/{issue_id}/vote
  
  def vote
    respond_to do |format|
      @issue_to_vote = Issue.find(params[:id])
      if !Vote.exists?(:issue_id => @issue_to_vote.id, :user_id => current_user.id)
        @vote = Vote.new
        @vote.user_id = current_user.id
        @vote.issue_id = @issue_to_vote.id
        @vote.save
        @issue_to_vote.increment!("Votes")
      else
        @vote = Vote.where(issue_id: params[:id], user_id: current_user.id).take
        @vote.destroy
        @issue_to_vote.decrement!("Votes")
      end
      format.html { redirect_to @issue_to_vote }
      format.json { render json: @issue_to_vote, status: :ok }
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { render json: {"message": "success"}, status: :ok }
    end
  end

  def show_attachment
    @issue = Issue.find(params[:id])
    respond_to do |format|
      if @issue.attachment.file?
        format.json {render json: @issue, status: :ok, serializer: IssueattachmentSerializer}
      else
        format.json {render json: {}, status: :ok}
      end
    end
  end

  def create_attachment
    @issue = Issue.find(params[:id])
    if @issue.user.id == current_user.id
      @issue.attachment = Paperclip.io_adapters.for(params[:file])
      @issue.save
    end
    respond_to do |format|
      if @issue.user.id == current_user.id
        format.json {render json: @issue, status: :created, serializer: IssueattachmentSerializer}
      else
        format.json {render json: {error: "Forbidden, you are not the creator of this issue"}, status: :forbidden}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
      render json: { error: 'Issue not found' }, status: :not_found if @issue.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.permit(:Title, :Description, :Type, :Priority, :Status, :assignee_id, :user_id, :attachment)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="input-group">
    <%= form.label :Title %>
    <%= form.text_field :Title, id: :issue_Title %>
  </div>

  <div class="input-group">
    <%= form.label :Description %>
    <%= form.text_area :Description, id: :issue_Description %>
  </div>

  <div class="input-group">
    <%= form.label :Type %>
    <%= form.select :Type, options_for_select(Issue.type, issue[:Type]), prompt: true, :class => 'genForm_dropBox' %>
  </div>

  <div class="input-group">
    <%= form.label :Priority %>
    <%= form.select :Priority, options_for_select(Issue.priority, issue[:Priority]), prompt: true, :class => 'genForm_dropBox' %>
  </div>

  <div class="input-group">
    <%= form.label :Status %>
    <%= form.select :Status, options_for_select(Issue.status), :class => 'genForm_dropBox' %>
  </div>

  <div class="input-group">
    <%= form.label :Assignee %>
    <%= form.collection_select :assignee_id, User.all, :id, :name, {:include_blank => 'No assigned user'} %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'submit' %>
    <%= link_to 'Cancel', issues_path, :class => 'cancel' %>
  </div>
  
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

app/views/issues/index.html.erb
<!DOCTYPE html>

<div class="header">
  <div class="section-title">
    <h1>Issues</h1>
  </div>
  <div class="page-actions">
    <% if current_user %>
      <%= link_to new_issue_path, class: 'create-button' do %>
        <span class="glyphicon glyphicon-plus"></span>
        <span class="createi-button">Create issue</span>
      <% end %>
      <%= link_to destroy_user_session_path, class: 'create-button' do %>
        <span class="glyphicon glyphicon-log-out"></span>
        <span class="createi-button">Log out</span>
      <% end %>
    <% end %>
  </div>
</div>


<div class="issues">

  <div class="issues-toolbar">
    <div class="filter-container">
      <p class="filter-label">Filters:</p>
      <ul class="filter-status">
        <li id="all" class="aui-button">
          <a href="/issues">All</a>
        </li>
        
        <li id="open" class="aui-button">
          <a><%= link_to "Open", issues_url(status: "New&Open")%></a>
        </li>
      
        <li id="mine" class="aui-button">
          <a><%= link_to "My issues", issues_url(assignee: current_user.id)%></a>
        </li>
      
        <li id="watching" class="aui-button">
          <a><%= link_to "Watching", issues_url(watcher: current_user.id)%></a>
        </li>
      </ul>
    </div>
  </div>

  <h2>Issues (<%= @issues.size %>)</h2>

  <p id="issues-filter-criteria">
    <% if request.query_parameters[:type] %>
      <b>type:</b> "<%= request.query_parameters[:type] %>"
    <% end %>
    <% if request.query_parameters[:priority] %>
        <b>priority:</b> "<%= request.query_parameters[:priority] %>"
    <% end %>
    <% if request.query_parameters[:status] %>
        <b>status:</b> "<%= request.query_parameters[:status] %>"
    <% end %>
    <% if request.query_parameters[:assignee] %>
        <b>assignee:</b> "<%= User.find(request.query_parameters[:assignee]).name %>"
    <% end %>
  </p>

  <table class="issue-list">
    <thead>
      <tr>
          <th scope="col">Title</th>
          <th scope="col">Type</th>
          <th scope="col">Priority</th>
          <th scope="col">Status</th>
          <th scope="col">Votes</th>
          <th scope="col">Assignee</th>
          <th scope="col">Created</th>
          <th scope="col">Updated</th>
          <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
      <tbody>
        <% @issues.each do |issue| %>
          <tr><!--@products = Product.status("active").starts_with("Ruby")-->
            <td><%= link_to issue.Title , issue, class:"btn-link" %></td>
            <td><%= link_to issue.Type , issues_url(type: issue.Type), class:"btn-link" %></td>
            <td><%= link_to issue.Priority , issues_url(priority: issue.Priority), class:"btn-link" %></td>
            <td><%= link_to issue.Status , issues_url(status: issue.Status), class:"btn-link" %></td>
            <td><%= issue.Votes %></td>
            <% if !issue.assignee.nil? %>
            <td><%= link_to issue.assignee.name, issues_url(assignee: issue.assignee.id), class:"btn-link" %></td>
            <% else %>
            <td></td>
            <% end %>
            <td><%= time_ago_in_words(issue.created_at) + " ago" %></td>
            <td><%= time_ago_in_words(issue.updated_at) + " ago" %></td>
            <td>
            <% if !Watcher.exists?(:issue_id => issue.id, :user_id => current_user.id) %>
                <%= link_to 'Watch', watch_url(id: issue.id, view: "index"), method: :post %>
            <%else %>
                <%= link_to 'Unwatch', watch_url(id: issue.id, view: "index"), method: :post %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <div class="section-title">
    <h1><%= @issue.Title %></h1>
  </div>
  <div class="page-actions">
    <% if current_user %>
      <%= link_to new_issue_path, class: 'create-button' do %>
        <span class="add-icon">+</span>
        <span class="createi-button">Create issue</span>
      <% end %>
      <%= link_to issues_url, class: 'create-button' do %>
        <span class="createi-button">Back</span>
      <% end %>
    <% end %>
  </div>
</div>

<div class="main-view">
  <div class="issue-header">
    <span class="issue-id">
      Issue #<%= @issue.id %>
    </span>
    <span class="issue-status">
      <%= @issue.Status %>
    </span>
    <div class="issue-toolbar">
      
      <% if current_user %>
          
          <div class="dropdown">
            <span style="margin-right:5px; background: #8D8DF4; padding:8px; font-weight: bold">
              <% if @issue.Status == "Open" || @issue.Status == "New" %>
                <a class="resolved"> <%= link_to 'Resolve', update_status_url(id: @issue.id, status: "Resolved"), method: :put %> </a>
              <% else %>
                <%= link_to 'Open', update_status_url(id: @issue.id, status: "Open"), method: :put, class:'open'%>
              <% end %>
            </span>
            
              <button class="show-button dropdown-toggle next-to" type="button" data-toggle="dropdown">Workflow
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <% Issue.status.each do |status| %>
                  <% if status != @issue.Status %>
                    <%= content_tag(:li, link_to(status, update_status_url(id: @issue.id, status: status), method: :put)) %>
                  <% end %>
                <% end %>
              </ul>
              <a href="#" data-toggle="modal" data-target="#attachmodal" class="show-button">Attach</a>

              <a href="/issues/<%= @issue.id %>/edit" class="show-button">Edit</a>
            
              <%= link_to 'Delete', @issue,  method: :delete, class: 'show-button', data: { confirm: 'Are you sure you want to delete this issue?' } %>
          </div>
      
          
      <% end %>
    </div>
  </div>
  
  <div class="issue-main-content">
    
    <div class="issue-info">

      <div class="issue-author">
        <span title="author-name"><b><%= @issue.user.name %></b></span>
        created an issue <time class="created_at"><%= @issue.created_at.strftime('%Y-%m-%d')%></time>
      </div>

      <div class="issue-description">
        <% if !(@issue.Description == "") %>
            <p class="description"><%= @issue.Description %></p>
        <% else %>
            <p class="no-description">No description provided.</p>

        <% end %>
      </div>

      <div class="issue-attachment">
          <% if @issue.attachment.file? %>
              <p>Attachment<a class="attachment-url" href=<%= @issue.attachment.url %> > <%=@issue.attachment.original_filename%></a> last updated <%=time_ago_in_words(Time.at(@issue.attachment.updated_at))%></p>
              <p>Content type <%=@issue.attachment.content_type%></p>
              <% if @issue.attachment.content_type.include? 'image/' %>
                  <div class="attachment-image">
                    <a class="attachment-url" href=<%= @issue.attachment.url %> ><%= image_tag @issue.attachment.url(:thumb) %> </a>
                  </div>
              <%end%>
          <% end %>
      </div>
      
      <div class="sidebar">
        <div class="issue-attrs">
          <dl>
            <dt>Assigned to</dt>
            <dd>
              <% if !@issue.assignee.nil? %>
              <a href="/issues?assignee=<%= @issue.assignee.id%>">
                <span title="assignee"><%= @issue.assignee.name%></span>
              </a>
              <% else %>
              No one assigned
              <% end %>
            </dd>
          </dl>
          
          <dl>
            <dt>Type</dt>
            <dd class="type with-icon">
              <%= link_to @issue.Type, issues_url(type: @issue.Type) %>
            </dd>
          </dl>
          
          <dl>
            <dt>Priority</dt>
            <dd class="priority with-icon">
              <%= link_to @issue.Priority, issues_url(priority: @issue.Priority) %>
            </dd>
          </dl>
          
          <dl>
            <dt>Status</dt>
            <dd class="status with-icon">
              <%= link_to @issue.Status, issues_url(status: @issue.Status) %>
            </dd>
          </dl>
          
          <dl>
            <dt>Votes</dt>
            <dd class="votes">
                <%= @issue.Votes %>
                  <% if !Vote.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
                  <%= link_to 'Vote for this issue', vote_url(id: @issue.id), method: :post, class:"vote" %>
                  <% else %>
                  <%= link_to 'Remove vote', vote_url(id: @issue.id), method: :post, class:"vote" %>
                  <% end %>
              </span>
            </dd>
          </dl>
          
          <dl>
            <dt>Watchers</dt>
            <dd class="watchers">
                <%= @issue.Watchers %>
                  <% if !Watcher.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
                  <%= link_to 'Watch this issue', watch_url(id: @issue.id, view: "issue"), method: :post, class: "vote" %>
                  <% else %>
                  <%= link_to 'Stop watching', watch_url(id: @issue.id, view: "issue"), method: :post, class: "vote" %>
                  <% end %>
              </span>
            </dd>
          </dl>
          
        </div>
      </div>
      
      <hr>
      
      <div class="issue-comments-container">
        
        <h2>Comments (<%= @issue.comments.size %>)</h2>
        
        <% @issue.comments.each do |comment| %>
          <div class="comentari">
            
            <p class="comenter">
              <%= comment.user.name %>
            </p>
           
            <p class="coment">
              <%= comment.body %>
              </br>
              <% if comment.attachment.file? %>
                <div class="attachment-image">
                  <%= image_tag comment.attachment.url(:medium) %>
                </div>
              <% end %>         
            </p>
            
            <%= time_ago_in_words(comment.created_at) + " ago" %>
              <% if comment.user.id == current_user.id %>
          |   <%= link_to 'Delete Comment', [comment.issue, comment],
                       method: :delete,
                       data: { confirm: 'Are you sure?' } , class: "esborrar" %>
              <% end %>
            
          </div>
          </br>
        <% end %>
        
        <%= form_with(model: [@issue, @issue.comments.build], local: true) do |form| %>
          <div class="input-group">
            <%= form.text_area :body, placeholder:'What do you want to say?' %>
            <%= form.file_field :attachment %>
          </div>
          <div class="actions">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>

<div class="modal fade" id="attachmodal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Attach a file</h4>
      </div>
      <div class="modal-body">
        <%= form_with(model: @issue, local: true) do |form| %>
          <%= form.file_field :attachment %>
          <%= form.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>